import { FormEvent, ReactNode, useEffect, useState } from 'react'
import { Link, Navigate, NavLink, Route, Routes, useNavigate } from 'react-router-dom'
import { isSupabaseConfigured, requireSupabase, supabase } from './lib/supabase'

const products = [
  ['Ceramic Mug', '$18.00', '24 in stock', 'mug'], ['Canvas Tote', '$32.00', '12 in stock', 'tote'], ['Scented Candle', '$28.00', '4 in stock', 'candle'], ['Hand Soap', '$20.00', '18 in stock', 'soap'], ['Olive Oil', '$22.00', '14 in stock', 'oil'], ['Tea Blend', '$16.00', '30 in stock', 'tea'], ['Wool Scarf', '$48.00', '5 in stock', 'scarf'], ['T-Shirt', '$36.00', '9 in stock', 'shirt'],
]
const nav = [['⌂', 'Dashboard', '/dashboard'], ['⌁', 'Sell', '/register'], ['▦', 'Products', '/products'], ['▤', 'Orders', '/orders'], ['♧', 'Customers', '/customers'], ['▥', 'Reports', '/reports'], ['⚙', 'Settings', '/settings']]
function Mark() { return <span className="leaf-mark">⌁</span> }
function Brand({ dark = false }: { dark?: boolean }) { return <Link className={`brand ${dark ? 'brand-dark' : ''}`} to="/"><Mark />Counterline <small>FOR INDEPENDENT RETAIL</small></Link> }
function Button({ children, to, pale = false }: { children: ReactNode, to?: string, pale?: boolean }) { const c = `cta ${pale ? 'cta-pale' : ''}`; return to ? <Link className={c} to={to}>{children}<b>→</b></Link> : <button className={c}>{children}<b>→</b></button> }

function Landing() { return <div className="landing"><header className="site-header"><Brand /><nav><a href="#product">Product</a><a href="#features">Features</a><a href="#retailers">Retailers</a><a href="#pricing">Pricing</a><a href="#resources">Resources</a></nav><div className="header-actions"><Link to="/login">Sign in</Link><Button to="/signup">Open your store</Button></div></header><section className="hero"><div className="hero-copy"><p className="kicker">OFFLINE-FIRST POS FOR INDEPENDENT RETAILERS</p><h1>Keep the<br /><i>counter</i> moving.</h1><span className="brush" /><p className="hero-text">Counterline gives independent retailers a register that stays clear, calm, and ready to sell — online or offline.</p><div className="hero-actions"><Button to="/signup">Open your store</Button><a className="watch" href="#product"><span>▷</span> See how it works</a></div><div className="hero-proof">{[['⌁','Offline-ready','Keep selling, always.'],['ϟ','Fast setup','Be live in minutes.'],['⌂','Built for real stores','Not just big chains.'],['▥','Insights that matter','Understand your business.']].map(([icon,title,copy]) => <article key={title}><span>{icon}</span><strong>{title}</strong><small>{copy}</small></article>)}</div></div><div className="hero-art"><div className="sunbeam" /><div className="monitor"><RegisterMini /></div><p className="vertical-note">LOCAL GOODS<br />KINDER COMMERCE</p></div></section><section id="features" className="feature-strip"><div className="strip-quote">Independent<br />Retail<br />Stronger<br />Together.</div>{[['♙','Sell anywhere','Works online and offline.'],['♧','Simple for your team','Easy to learn. Easy to run.'],['⬡','Your data, your control','Secure, reliable and transparent.'],['⌁','Built for what’s next','Scale as you grow.']].map(([icon,title,copy]) => <article key={title}><span>{icon}</span><strong>{title}</strong><small>{copy}</small></article>)}<div className="metrics"><b>10K+</b><small>Retailers trust Counterline</small><b>99.9%</b><small>Sales never blocked by network issues</small></div></section><footer><Brand dark /><span>MORE THAN A POS. A PARTNER IN THE EVERYDAY.</span><Button to="/signup">Start for free</Button></footer></div> }
function RegisterMini() { return <div className="mini-register"><aside><b>Counterline</b><span>▣ &nbsp; Sell</span><span>▦ &nbsp; Products</span><span>▤ &nbsp; Orders</span><span>♧ &nbsp; Customers</span></aside><div className="mini-products"><div className="mini-search">⌕ &nbsp; Search products, scan barcode, or enter SKU...</div><div className="mini-grid">{products.slice(0, 6).map(([name,,stock,art]) => <div className="mini-card" key={name}><div className={`product-art ${art}`} /><b>{name}</b><small>{stock}</small></div>)}</div></div><div className="mini-cart"><p>Current Sale</p><div>☕ &nbsp; Ceramic Mug <b>$18.00</b></div><div>▱ &nbsp; Canvas Tote <b>$32.00</b></div><hr /><strong>Total <b>$53.44</b></strong><button>Proceed to Payment →</button></div></div> }

function AuthShell({ title, copy, children }: { title: string, copy: string, children: ReactNode }) { return <main className="auth-page"><section className="auth-art"><Brand dark /><div><p className="kicker">RETAIL, UNINTERRUPTED</p><h1>{title}</h1><p>{copy}</p></div><div className="auth-note"><Mark /><span>SELL TODAY.<br />A BRIGHTER TOMORROW.</span></div></section><section className="auth-form"><div className="form-card">{children}</div></section></main> }
function AuthNotice({ error, message }: { error?: string, message?: string }) { return <>{error && <p className="form-notice error">{error}</p>}{message && <p className="form-notice">{message}</p>}</> }
async function finishStoreSetup() {
  const client = requireSupabase()
  const { data: { user } } = await client.auth.getUser()
  if (!user) throw new Error('Your session could not be restored. Please sign in again.')
  await client.rpc('accept_store_invites')
  const { data: memberships, error } = await client.from('store_memberships').select('store_id').eq('user_id', user.id).eq('active', true).limit(1)
  if (error) throw error
  if (!memberships?.length && typeof user.user_metadata.store_name === 'string') {
    const { error: createError } = await client.rpc('create_store', { p_name: user.user_metadata.store_name, p_timezone: Intl.DateTimeFormat().resolvedOptions().timeZone, p_currency: 'USD' })
    if (createError) throw createError
  }
}
function Login() { const go = useNavigate(); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const submit = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); setError(''); setBusy(true); try { const form = new FormData(e.currentTarget); const client = requireSupabase(); const { error: signInError } = await client.auth.signInWithPassword({ email: String(form.get('email')), password: String(form.get('password')) }); if (signInError) throw signInError; await finishStoreSetup(); go('/dashboard') } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to sign in.') } finally { setBusy(false) } }; return <AuthShell title="Your store is waiting." copy="Sign in to manage your store, team, and register setup."><p className="kicker">OWNER & MANAGER ACCESS</p><h2>Welcome back.</h2><p className="form-copy">Cashiers use the separate POS PIN screen when it is implemented.</p><AuthNotice error={error} />{!isSupabaseConfigured && <p className="form-notice">Demo mode is active. Add your Supabase values to enable sign-in.</p>}<form onSubmit={submit}><label>Email address<input name="email" type="email" placeholder="you@yourstore.com" required /></label><label>Password<input name="password" type="password" placeholder="Enter your password" required /></label><div className="form-line"><label className="checkbox"><input type="checkbox" /> Keep me signed in</label><a href="#support">Need help?</a></div><Button>{busy ? 'Signing in…' : 'Open store'}</Button></form><p className="form-footer">New to Counterline? <Link to="/signup">Create your store</Link></p></AuthShell> }
function Signup() { const go = useNavigate(); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const submit = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); setError(''); setMessage(''); setBusy(true); try { const form = new FormData(e.currentTarget); const storeName = String(form.get('storeName')).trim(); const client = requireSupabase(); const { data, error: signUpError } = await client.auth.signUp({ email: String(form.get('email')), password: String(form.get('password')), options: { data: { full_name: String(form.get('fullName')).trim(), store_name: storeName }, emailRedirectTo: `${window.location.origin}/login` } }); if (signUpError) throw signUpError; if (!data.session) { setMessage('Check your email to confirm your account. Then sign in to create your store.'); return } await finishStoreSetup(); go('/dashboard') } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to create your store.') } finally { setBusy(false) } }; return <AuthShell title="A good store starts here." copy="Set up the owner account for your store. You can invite your team after sign-in."><p className="kicker">START YOUR STORE</p><h2>Make it yours.</h2><p className="form-copy">This creates an owner account and your first store workspace.</p><AuthNotice error={error} message={message} /><form onSubmit={submit}><label>Your name<input name="fullName" placeholder="Your full name" required /></label><label>Store name<input name="storeName" placeholder="Riverside General" required /></label><label>Work email<input name="email" type="email" placeholder="owner@yourstore.com" required /></label><label>Create password<input name="password" type="password" minLength={12} placeholder="At least 12 characters" required /></label><Button>{busy ? 'Creating store…' : 'Create store'}</Button></form><p className="form-footer">Already have access? <Link to="/login">Sign in</Link></p></AuthShell> }
function Invite() { const go = useNavigate(); const [error, setError] = useState(''); const [message, setMessage] = useState(''); const accept = async () => { setError(''); setMessage(''); try { const client = requireSupabase(); const { data: { user } } = await client.auth.getUser(); if (!user) { go('/login'); return } const { data, error: acceptError } = await client.rpc('accept_store_invites'); if (acceptError) throw acceptError; if (data) { go('/dashboard'); return } setMessage('No active invitation was found for this signed-in email.') } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to accept your invitation.') } }; return <AuthShell title="The good stuff is ahead." copy="Sign in with the same email your manager invited to join the store."><p className="kicker">JOIN YOUR TEAM</p><h2>Accept your invite.</h2><p className="form-copy">Invitations are matched to your verified account email. No invite code is needed.</p><AuthNotice error={error} message={message} /><button className="cta" onClick={accept}>Check my invitation <b>→</b></button><p className="form-footer"><Link to="/login">Back to sign in</Link></p></AuthShell> }

function AppLayout({ children }: { children: ReactNode }) { const mobileNav = nav.slice(0, 5); return <div className="pos-app"><aside className="app-sidebar"><Brand dark /> <nav>{nav.map(([icon,label,to]) => <NavLink key={label} to={to}><span>{icon}</span>{label}</NavLink>)}</nav><div className="sidebar-bottom"><span>⌂ &nbsp; Riverside General<br /><small>Register 01</small></span><span>● &nbsp; Jamie Park<br /><small>Cashier</small></span></div></aside><main className="app-main"><header className="app-top"><div className="mobile-store"><Brand dark /></div><div className="connection">● Offline · 3 pending</div><button className="sync">↻</button><span className="register-meta"><b>Register 01</b><small>Riverside General</small></span><span className="clock">Mon, Sep 15 · 10:24 AM</span></header>{children}</main><nav className="mobile-nav">{mobileNav.map(([icon,label,to]) => <NavLink key={label} to={to}><span>{icon}</span>{label}</NavLink>)}</nav></div> }
function Register() { return <AppLayout><section className="register-page"><div className="catalog"><div className="catalog-tools"><div className="search">⌕ &nbsp; Search products, scan barcode, or enter SKU... <b>▥</b></div><div className="categories">{['All','Coffee','Home','Apparel','Wellness','Stationery','Food','More⌄'].map((x,i) => <button className={i===0?'active':''} key={x}>{x}</button>)}</div></div><div className="catalog-grid">{products.map(([name,price,stock,art]) => <button className="catalog-card" key={name}><div className={`product-art ${art}`} /><strong>{name}</strong><span>{price}</span><small className={stock.startsWith('4')||stock.startsWith('5')?'low':''}>✓ &nbsp;{stock}</small></button>)}</div></div><Cart /></section></AppLayout> }
function Cart(){ return <aside className="sale-cart"><div className="cart-title"><h2>Current Sale</h2><a>Clear</a><b>•••</b></div>{[['Ceramic Mug','$18.00','2'],['Canvas Tote','$32.00','1']].map(([n,p,q])=><div className="cart-line" key={n}><div className={`tiny-art ${n.includes('Mug')?'mug':'tote'}`} /><span><b>{n}</b><small>{p}</small></span><div className="quantity">− &nbsp; {q} &nbsp; +</div><strong>{n.includes('Mug')?'$36.00':'$32.00'}</strong><button>×</button></div>)}<button className="customer">♧ &nbsp; Add customer (optional)</button><div className="totals"><span>Subtotal <b>$68.00</b></span><span>Tax (8%) <b>$5.44</b></span><strong>Total <b>$73.44</b></strong></div><Button to="/payment">Proceed to Payment</Button></aside> }
function Dashboard(){ return <AppLayout><section className="dashboard"><p className="kicker">MONDAY, SEPTEMBER 15, 2026</p><h1>Good morning, Jamie.</h1><p className="subtitle">Ready for a productive day?</p><div className="stat-row">{[['Today’s Sales','$1,248.50','↗ +12% vs. yesterday'],['Transactions','32','↗ +6% vs. yesterday'],['Average Sale','$39.02','↗ +8% vs. yesterday'],['Items Sold','84','↗ +15% vs. yesterday']].map(([l,n,d])=><article key={l}><small>{l}</small><b>{n}</b><span>{d}</span></article>)}</div><div className="dash-grids"><article className="chart"><h3>Sales Overview <button>Today⌄</button></h3><div className="bars">{[23,38,25,54,72,41,67,91,58,44,29,31].map((v,i)=><i style={{height:`${v}%`}} key={i}/>)}</div><small>8AM　　　10AM　　　12PM　　　2PM　　　4PM　　　6PM　　　8PM</small></article><article className="top-products"><h3>Top Products <button>Today⌄</button></h3>{products.slice(0,5).map(([n,p])=><p key={n}><span>{n}</span><small>24 sold</small><b>{p}</b></p>)}</article></div><div className="health"><article>◉ <span><b>System Online</b><small>Last synced 5 mins ago</small></span></article><article>◒ <span><b>3 Pending</b><small>Sales waiting to sync</small></span></article><article>✓ <span><b>No Issues</b><small>All systems operational</small></span></article></div></section></AppLayout> }
function Payment(){ return <AppLayout><section className="payment-page"><div className="pay-main"><Link to="/register">← &nbsp; Back to Sale</Link><p className="kicker">PAYMENT</p><h1>Payment</h1><small>Total amount due</small><h2>$73.44</h2><p>Select payment method</p><div className="methods"><button className="selected">▣ &nbsp; Cash</button><button>▭ &nbsp; Card (External)</button><button>♧ &nbsp; Split Payment</button></div><label>Amount received<div className="money-input">$ &nbsp; 80.00</div></label><p>Quick amounts</p><div className="quick"><button>$73.44</button><button>$80.00</button><button>$100.00</button></div></div><aside className="payment-summary"><div className="change"><small>Change due</small><b>$6.56</b></div><div className="summary-lines"><span>Subtotal <b>$68.00</b></span><span>Tax (8%) <b>$5.44</b></span><span>Total <b>$73.44</b></span><span>Amount received <b>$80.00</b></span><strong>Change due <b>$6.56</b></strong></div><Button>Complete Sale</Button><button className="print">▣ &nbsp; Print Receipt</button></aside></section></AppLayout> }
function Settings() { const [storeId, setStoreId] = useState(''); const [role, setRole] = useState(''); const [error, setError] = useState(''); const [message, setMessage] = useState(''); useEffect(() => { const load = async () => { if (!supabase) return; const { data: { user } } = await supabase.auth.getUser(); if (!user) return; const { data } = await supabase.from('store_memberships').select('store_id, role').eq('user_id', user.id).eq('active', true).limit(1); if (data?.[0]) { setStoreId(data[0].store_id); setRole(data[0].role) } }; load() }, []); const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(''); setMessage(''); try { const form = new FormData(event.currentTarget); const client = requireSupabase(); const { error: inviteError } = await client.rpc('invite_store_member', { p_store_id: storeId, p_email: String(form.get('email')), p_role: String(form.get('role')) }); if (inviteError) throw inviteError; setMessage('Staff invitation saved. Ask the person to sign up or sign in with this email, then use the invitation screen.'); event.currentTarget.reset() } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to add this team member.') } }; const canInvite = role === 'owner' || role === 'manager'; return <AppLayout><section className="settings-page"><p className="kicker">STORE ADMINISTRATION</p><h1>Team access.</h1><p>Invite the people who manage your store. Cashier PIN setup will be added with the POS device flow.</p>{!isSupabaseConfigured && <p className="form-notice">Add your Supabase environment variables before inviting staff.</p>}{canInvite ? <form className="invite-form" onSubmit={submit}><label>Staff email<input name="email" type="email" placeholder="team@yourstore.com" required /></label><label>Store role<select name="role" defaultValue="cashier"><option value="cashier">Cashier</option><option value="manager">Manager</option></select></label><button className="cta" disabled={!storeId}>Add team member <b>→</b></button></form> : <p className="form-notice">Only an owner or manager can invite staff.</p>}<AuthNotice error={error} message={message} /></section></AppLayout> }
function Placeholder(){ return <AppLayout><section className="placeholder"><p className="kicker">TEAM WORKSPACE</p><h1>Page ready for its owner.</h1><p>This route is part of the shared foundation. Your assigned teammate can build its feature here without touching the register flow.</p></section></AppLayout> }
function App(){ return <Routes><Route path="/" element={<Landing/>}/><Route path="/login" element={<Login/>}/><Route path="/signup" element={<Signup/>}/><Route path="/invite" element={<Invite/>}/><Route path="/dashboard" element={<Dashboard/>}/><Route path="/register" element={<Register/>}/><Route path="/payment" element={<Payment/>}/><Route path="/products" element={<Placeholder/>}/><Route path="/orders" element={<Placeholder/>}/><Route path="/customers" element={<Placeholder/>}/><Route path="/reports" element={<Placeholder/>}/><Route path="/settings" element={<Settings/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes> }
export default App
